// Exports centralisés pour l'architecture @/src
export * from './types';
export * from './constants/patterns';
export * from './services/BarcodeService';
export * from './services/URLService';
export * from './hooks/useURLParams';
export * from './hooks/useValidation';
export * from './hooks/usePatternLogic';
export * from './hooks/useFooterHeight';
export * from './hooks/useAppState';
export * from './components/layout/AnimatedBackground';
export * from './components/layout/Header';
export * from './components/layout/Footer';
export * from './components/forms/InputForm';
export * from './components/forms/PatternSelector';
export * from './components/forms/ToggleButton';
export * from './components/forms/ValidateButton';
export * from './components/forms/FormSection';
export * from './components/display/BarcodeDisplay'; 